baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 20

[params]
  contentTypeName = "posts"
  themeColor = "lime"
  showMenuItems = 10
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  favicon = "favicon.ico"
  oneHeadingSize = false
  readingTime = true
  # Toc = false
  # TocTitle = "Table of Contents"

[languages]
  [languages.en]
    languageName = "English"
    title = "Dimitris Vagiakakos SV1SJP"
    subtitle = "eLearning"
    owner = "Dimitris Vagiakakos"
    keywords = "decentralized"
    copyright = "All rights reserved, TuxHouse Educational Technologies - Dimitris LinuxOS - 2011-2024"
    menuMore = "Show more useful stuff"
    readMore = "Read more stuff"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "No idea at all"
    missingBackButtonLabel = "Try to find the Penguin somewhere else."

    [languages.en.params]
      [languages.en.params.logo]
        logoText = "Dimitris Vagiakakos SV1SJP"
        logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "whoami"
        name = "$whoami"
        url = "/whoami"
     
      [[languages.en.menu.main]]
        identifier = "micro-blogging"
        name = "micro-blogging"
        url = "https://fosstodon.org/@sv1sjp"
     
      [[languages.en.menu.main]]
        identifier = "Blockchain Camera"
        name = "Blockchain Camera"
        url = "/Blockchain_Camera"
        
      [[languages.en.menu.main]]
        identifier = "Projects"
        name = "Projects"
        url = "/Projects"
        
      [[languages.en.menu.main]]
        identifier = "Blockchain WriteUps"
        name = "Blockchain WriteUps"
        url = "/Blockchain_WriteUps"
	
      [[languages.en.menu.main]]
        identifier = "Greek Articles"
        name = "Greek Articles"
        url = "/Greek_Articles"
        
      [[languages.en.menu.main]]
        identifier = "Panellinies_AEPP"
        name = "Panellinies_AEPP"
        url = "/Panellinies_AEPP/index.html"
        
      [[languages.en.menu.main]]
        identifier = "Videos"
        name = "Videos"
        url = "https://odysee.com/@TuxHouse:1"
        
      [[languages.en.menu.main]]
        identifier = "Ubuntel"
        name = "Ubuntel"
        url = "/Ubuntel"
        
      [[languages.en.menu.main]]
        identifier = "About TuxHouse"
        name = "About TuxHouse"
        url = "/about"
